<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="qa.glassbeam.com" tests="1" failures="1" timestamp="26 Dec 2013 17:51:33 GMT" time="0.043" errors="0">
  <testcase name="testAdd" time="0.025" classname="TestNGSimpleTest">
    <failure type="java.lang.AssertionError" message="expected [TestNG is working fine] but found [TestNG is working 1111fine]">
      <![CDATA[java.lang.AssertionError: expected [TestNG is working fine] but found [TestNG is working 1111fine]
	at TestNGSimpleTest.testAdd(TestNGSimpleTest.java:8)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:158)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:98)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)
	at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)
	at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- testAdd -->
</testsuite>
